name: Reset packages
on:
  workflow_dispatch: {}
jobs:
  packages:
    runs-on: ubuntu-latest
    container: bioconductor/bioc-redis:RELEASE_3_15
    steps:
      - uses: actions/checkout@v3
        with:
          #token: ${{ secrets.PAT }}
          persist-credentials: true
      - shell: sh
        run: |
          Rscript deps_json.R packages.json
          cp packages.json original.json
          python3 -c 'import json; f = open("packages.json", "r"); pkgs = json.load(f); f.close(); f = open("packages.json", "w"); f.write(json.dumps(pkgs, indent=4)); f.close()'
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add packages.json
          git add original.json
          git commit -m "Reset packages"
          git push
        env:
          GITHUB_PAT: ${{ secrets.GIT_PAT }}